/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package visGrid.impl;
import java.util.HashMap;
        import java.util.Map;
        import java.util.Timer;
        import java.util.TimerTask;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import visGrid.Battery;
import visGrid.VisGridPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Battery</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link visGrid.impl.BatteryImpl#getGenerator_mode <em>Generator mode</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getGenerator_status <em>Generator status</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getRfb_size <em>Rfb size</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getPower_type <em>Power type</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getPower_set_high <em>Power set high</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getPower_set_low <em>Power set low</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getRinternal <em>Rinternal</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getV_Max <em>VMax</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getI_Max <em>IMax</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getE_Max <em>EMax</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getEnergy <em>Energy</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getEfficiency <em>Efficiency</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getBase_efficiency <em>Base efficiency</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getRated_kVA <em>Rated kVA</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getV_Out <em>VOut</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getI_Out <em>IOut</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getVA_Out <em>VA Out</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getV_In <em>VIn</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getI_In <em>IIn</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getV_Internal <em>VInternal</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getI_Internal <em>IInternal</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getI_Prev <em>IPrev</em>}</li>
 *   <li>{@link visGrid.impl.BatteryImpl#getPhases <em>Phases</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class BatteryImpl extends ConnectionImpl implements Battery {
	// Generated by python script located in this directory
       boolean threadLock = false;
       HashMap<String,Boolean> lock = new HashMap<String,Boolean>();

   private void checkUnlock() {
        if (threadLock) return;
        for (Map.Entry<String, Boolean> entry : lock.entrySet()){
            if (threadLock) return;
            if (entry.getValue() == false) return;
        }
        resetLock();
    }

    private void resetLock() {
        Timer timer = new Timer();
        class Task extends TimerTask{
            public void run() {
                threadLock = true;
                for (Map.Entry<String, Boolean> entry : lock.entrySet()){
                    entry.setValue(false);
                }
                threadLock = false;
            }   
        }
        timer.schedule(new Task(), lock.size()*30);
    }
    // END PYTHON GENERATED CODE
	/**
	 * The default value of the '{@link #getGenerator_mode() <em>Generator mode</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerator_mode()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATOR_MODE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGenerator_mode() <em>Generator mode</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerator_mode()
	 * @generated
	 * @ordered
	 */
	protected String generator_mode = GENERATOR_MODE_EDEFAULT;

	/**
	 * The default value of the '{@link #getGenerator_status() <em>Generator status</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerator_status()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATOR_STATUS_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGenerator_status() <em>Generator status</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerator_status()
	 * @generated
	 * @ordered
	 */
	protected String generator_status = GENERATOR_STATUS_EDEFAULT;

	/**
	 * The default value of the '{@link #getRfb_size() <em>Rfb size</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRfb_size()
	 * @generated
	 * @ordered
	 */
	protected static final String RFB_SIZE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getRfb_size() <em>Rfb size</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRfb_size()
	 * @generated
	 * @ordered
	 */
	protected String rfb_size = RFB_SIZE_EDEFAULT;

	/**
	 * The default value of the '{@link #getPower_type() <em>Power type</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPower_type()
	 * @generated
	 * @ordered
	 */
	protected static final String POWER_TYPE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getPower_type() <em>Power type</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPower_type()
	 * @generated
	 * @ordered
	 */
	protected String power_type = POWER_TYPE_EDEFAULT;

	/**
	 * The default value of the '{@link #getPower_set_high() <em>Power set high</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPower_set_high()
	 * @generated
	 * @ordered
	 */
	protected static final String POWER_SET_HIGH_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getPower_set_high() <em>Power set high</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPower_set_high()
	 * @generated
	 * @ordered
	 */
	protected String power_set_high = POWER_SET_HIGH_EDEFAULT;

	/**
	 * The default value of the '{@link #getPower_set_low() <em>Power set low</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPower_set_low()
	 * @generated
	 * @ordered
	 */
	protected static final String POWER_SET_LOW_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getPower_set_low() <em>Power set low</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPower_set_low()
	 * @generated
	 * @ordered
	 */
	protected String power_set_low = POWER_SET_LOW_EDEFAULT;

	/**
	 * The default value of the '{@link #getRinternal() <em>Rinternal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRinternal()
	 * @generated
	 * @ordered
	 */
	protected static final String RINTERNAL_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getRinternal() <em>Rinternal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRinternal()
	 * @generated
	 * @ordered
	 */
	protected String rinternal = RINTERNAL_EDEFAULT;

	/**
	 * The default value of the '{@link #getV_Max() <em>VMax</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_Max()
	 * @generated
	 * @ordered
	 */
	protected static final String VMAX_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getV_Max() <em>VMax</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_Max()
	 * @generated
	 * @ordered
	 */
	protected String v_Max = VMAX_EDEFAULT;

	/**
	 * The default value of the '{@link #getI_Max() <em>IMax</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Max()
	 * @generated
	 * @ordered
	 */
	protected static final String IMAX_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getI_Max() <em>IMax</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Max()
	 * @generated
	 * @ordered
	 */
	protected String i_Max = IMAX_EDEFAULT;

	/**
	 * The default value of the '{@link #getE_Max() <em>EMax</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getE_Max()
	 * @generated
	 * @ordered
	 */
	protected static final String EMAX_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getE_Max() <em>EMax</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getE_Max()
	 * @generated
	 * @ordered
	 */
	protected String e_Max = EMAX_EDEFAULT;

	/**
	 * The default value of the '{@link #getEnergy() <em>Energy</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEnergy()
	 * @generated
	 * @ordered
	 */
	protected static final String ENERGY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getEnergy() <em>Energy</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEnergy()
	 * @generated
	 * @ordered
	 */
	protected String energy = ENERGY_EDEFAULT;

	/**
	 * The default value of the '{@link #getEfficiency() <em>Efficiency</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEfficiency()
	 * @generated
	 * @ordered
	 */
	protected static final String EFFICIENCY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getEfficiency() <em>Efficiency</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEfficiency()
	 * @generated
	 * @ordered
	 */
	protected String efficiency = EFFICIENCY_EDEFAULT;

	/**
	 * The default value of the '{@link #getBase_efficiency() <em>Base efficiency</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getBase_efficiency()
	 * @generated
	 * @ordered
	 */
	protected static final String BASE_EFFICIENCY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getBase_efficiency() <em>Base efficiency</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getBase_efficiency()
	 * @generated
	 * @ordered
	 */
	protected String base_efficiency = BASE_EFFICIENCY_EDEFAULT;

	/**
	 * The default value of the '{@link #getRated_kVA() <em>Rated kVA</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRated_kVA()
	 * @generated
	 * @ordered
	 */
	protected static final String RATED_KVA_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getRated_kVA() <em>Rated kVA</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRated_kVA()
	 * @generated
	 * @ordered
	 */
	protected String rated_kVA = RATED_KVA_EDEFAULT;

	/**
	 * The default value of the '{@link #getV_Out() <em>VOut</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_Out()
	 * @generated
	 * @ordered
	 */
	protected static final String VOUT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getV_Out() <em>VOut</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_Out()
	 * @generated
	 * @ordered
	 */
	protected String v_Out = VOUT_EDEFAULT;

	/**
	 * The default value of the '{@link #getI_Out() <em>IOut</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Out()
	 * @generated
	 * @ordered
	 */
	protected static final String IOUT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getI_Out() <em>IOut</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Out()
	 * @generated
	 * @ordered
	 */
	protected String i_Out = IOUT_EDEFAULT;

	/**
	 * The default value of the '{@link #getVA_Out() <em>VA Out</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVA_Out()
	 * @generated
	 * @ordered
	 */
	protected static final String VA_OUT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getVA_Out() <em>VA Out</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVA_Out()
	 * @generated
	 * @ordered
	 */
	protected String vA_Out = VA_OUT_EDEFAULT;

	/**
	 * The default value of the '{@link #getV_In() <em>VIn</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_In()
	 * @generated
	 * @ordered
	 */
	protected static final String VIN_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getV_In() <em>VIn</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_In()
	 * @generated
	 * @ordered
	 */
	protected String v_In = VIN_EDEFAULT;

	/**
	 * The default value of the '{@link #getI_In() <em>IIn</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_In()
	 * @generated
	 * @ordered
	 */
	protected static final String IIN_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getI_In() <em>IIn</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_In()
	 * @generated
	 * @ordered
	 */
	protected String i_In = IIN_EDEFAULT;

	/**
	 * The default value of the '{@link #getV_Internal() <em>VInternal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_Internal()
	 * @generated
	 * @ordered
	 */
	protected static final String VINTERNAL_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getV_Internal() <em>VInternal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getV_Internal()
	 * @generated
	 * @ordered
	 */
	protected String v_Internal = VINTERNAL_EDEFAULT;

	/**
	 * The default value of the '{@link #getI_Internal() <em>IInternal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Internal()
	 * @generated
	 * @ordered
	 */
	protected static final String IINTERNAL_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getI_Internal() <em>IInternal</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Internal()
	 * @generated
	 * @ordered
	 */
	protected String i_Internal = IINTERNAL_EDEFAULT;

	/**
	 * The default value of the '{@link #getI_Prev() <em>IPrev</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Prev()
	 * @generated
	 * @ordered
	 */
	protected static final String IPREV_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getI_Prev() <em>IPrev</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getI_Prev()
	 * @generated
	 * @ordered
	 */
	protected String i_Prev = IPREV_EDEFAULT;

	/**
	 * The default value of the '{@link #getPhases() <em>Phases</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPhases()
	 * @generated
	 * @ordered
	 */
	protected static final String PHASES_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getPhases() <em>Phases</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPhases()
	 * @generated
	 * @ordered
	 */
	protected String phases = PHASES_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BatteryImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return VisGridPackage.eINSTANCE.getBattery();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getGenerator_mode() {
		// Generated by python script located in this directory
			if (!lock.containsKey("generator_mode")) lock.put("generator_mode", new Boolean(false));
			if (!(Boolean)lock.get("generator_mode")){
				lock.put("generator_mode", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"generator_mode");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Generator_mode");
					generator_mode= val;
			}
		return generator_mode;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGenerator_mode(String newGenerator_mode) {
		String oldGenerator_mode = generator_mode;
		generator_mode = newGenerator_mode;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__GENERATOR_MODE, oldGenerator_mode, generator_mode));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getGenerator_status() {
		// Generated by python script located in this directory
			if (!lock.containsKey("generator_status")) lock.put("generator_status", new Boolean(false));
			if (!(Boolean)lock.get("generator_status")){
				lock.put("generator_status", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"generator_status");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Generator_status");
					generator_status= val;
			}
		return generator_status;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGenerator_status(String newGenerator_status) {
		String oldGenerator_status = generator_status;
		generator_status = newGenerator_status;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__GENERATOR_STATUS, oldGenerator_status, generator_status));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getRfb_size() {
		// Generated by python script located in this directory
			if (!lock.containsKey("rfb_size")) lock.put("rfb_size", new Boolean(false));
			if (!(Boolean)lock.get("rfb_size")){
				lock.put("rfb_size", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"rfb_size");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Rfb_size");
					rfb_size= val;
			}
		return rfb_size;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setRfb_size(String newRfb_size) {
		String oldRfb_size = rfb_size;
		rfb_size = newRfb_size;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__RFB_SIZE, oldRfb_size, rfb_size));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getPower_type() {
		// Generated by python script located in this directory
			if (!lock.containsKey("power_type")) lock.put("power_type", new Boolean(false));
			if (!(Boolean)lock.get("power_type")){
				lock.put("power_type", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"power_type");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Power_type");
					power_type= val;
			}
		return power_type;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setPower_type(String newPower_type) {
		String oldPower_type = power_type;
		power_type = newPower_type;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__POWER_TYPE, oldPower_type, power_type));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getPower_set_high() {
		// Generated by python script located in this directory
			if (!lock.containsKey("power_set_high")) lock.put("power_set_high", new Boolean(false));
			if (!(Boolean)lock.get("power_set_high")){
				lock.put("power_set_high", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"power_set_high");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Power_set_high");
					power_set_high= val;
			}
		return power_set_high;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setPower_set_high(String newPower_set_high) {
		String oldPower_set_high = power_set_high;
		power_set_high = newPower_set_high;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__POWER_SET_HIGH, oldPower_set_high, power_set_high));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getPower_set_low() {
		// Generated by python script located in this directory
			if (!lock.containsKey("power_set_low")) lock.put("power_set_low", new Boolean(false));
			if (!(Boolean)lock.get("power_set_low")){
				lock.put("power_set_low", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"power_set_low");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Power_set_low");
					power_set_low= val;
			}
		return power_set_low;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setPower_set_low(String newPower_set_low) {
		String oldPower_set_low = power_set_low;
		power_set_low = newPower_set_low;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__POWER_SET_LOW, oldPower_set_low, power_set_low));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getRinternal() {
		// Generated by python script located in this directory
			if (!lock.containsKey("rinternal")) lock.put("rinternal", new Boolean(false));
			if (!(Boolean)lock.get("rinternal")){
				lock.put("rinternal", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"rinternal");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Rinternal");
					rinternal= val;
			}
		return rinternal;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setRinternal(String newRinternal) {
		String oldRinternal = rinternal;
		rinternal = newRinternal;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__RINTERNAL, oldRinternal, rinternal));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getV_Max() {
		// Generated by python script located in this directory
			if (!lock.containsKey("v_Max")) lock.put("v_Max", new Boolean(false));
			if (!(Boolean)lock.get("v_Max")){
				lock.put("v_Max", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"v_Max");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"V_Max");
					v_Max= val;
			}
		return v_Max;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setV_Max(String newV_Max) {
		String oldV_Max = v_Max;
		v_Max = newV_Max;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__VMAX, oldV_Max, v_Max));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getI_Max() {
		// Generated by python script located in this directory
			if (!lock.containsKey("i_Max")) lock.put("i_Max", new Boolean(false));
			if (!(Boolean)lock.get("i_Max")){
				lock.put("i_Max", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"i_Max");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"I_Max");
					i_Max= val;
			}
		return i_Max;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setI_Max(String newI_Max) {
		String oldI_Max = i_Max;
		i_Max = newI_Max;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__IMAX, oldI_Max, i_Max));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getE_Max() {
		// Generated by python script located in this directory
			if (!lock.containsKey("e_Max")) lock.put("e_Max", new Boolean(false));
			if (!(Boolean)lock.get("e_Max")){
				lock.put("e_Max", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"e_Max");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"E_Max");
					e_Max= val;
			}
		return e_Max;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setE_Max(String newE_Max) {
		String oldE_Max = e_Max;
		e_Max = newE_Max;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__EMAX, oldE_Max, e_Max));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getEnergy() {
		// Generated by python script located in this directory
			if (!lock.containsKey("energy")) lock.put("energy", new Boolean(false));
			if (!(Boolean)lock.get("energy")){
				lock.put("energy", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"energy");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Energy");
					energy= val;
			}
		return energy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setEnergy(String newEnergy) {
		String oldEnergy = energy;
		energy = newEnergy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__ENERGY, oldEnergy, energy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getEfficiency() {
		// Generated by python script located in this directory
			if (!lock.containsKey("efficiency")) lock.put("efficiency", new Boolean(false));
			if (!(Boolean)lock.get("efficiency")){
				lock.put("efficiency", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"efficiency");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Efficiency");
					efficiency= val;
			}
		return efficiency;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setEfficiency(String newEfficiency) {
		String oldEfficiency = efficiency;
		efficiency = newEfficiency;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__EFFICIENCY, oldEfficiency, efficiency));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getBase_efficiency() {
		// Generated by python script located in this directory
			if (!lock.containsKey("base_efficiency")) lock.put("base_efficiency", new Boolean(false));
			if (!(Boolean)lock.get("base_efficiency")){
				lock.put("base_efficiency", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"base_efficiency");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Base_efficiency");
					base_efficiency= val;
			}
		return base_efficiency;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setBase_efficiency(String newBase_efficiency) {
		String oldBase_efficiency = base_efficiency;
		base_efficiency = newBase_efficiency;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__BASE_EFFICIENCY, oldBase_efficiency, base_efficiency));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getRated_kVA() {
		// Generated by python script located in this directory
			if (!lock.containsKey("rated_kVA")) lock.put("rated_kVA", new Boolean(false));
			if (!(Boolean)lock.get("rated_kVA")){
				lock.put("rated_kVA", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"rated_kVA");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Rated_kVA");
					rated_kVA= val;
			}
		return rated_kVA;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setRated_kVA(String newRated_kVA) {
		String oldRated_kVA = rated_kVA;
		rated_kVA = newRated_kVA;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__RATED_KVA, oldRated_kVA, rated_kVA));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getV_Out() {
		// Generated by python script located in this directory
			if (!lock.containsKey("v_Out")) lock.put("v_Out", new Boolean(false));
			if (!(Boolean)lock.get("v_Out")){
				lock.put("v_Out", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"v_Out");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"V_Out");
					v_Out= val;
			}
		return v_Out;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setV_Out(String newV_Out) {
		String oldV_Out = v_Out;
		v_Out = newV_Out;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__VOUT, oldV_Out, v_Out));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getI_Out() {
		// Generated by python script located in this directory
			if (!lock.containsKey("i_Out")) lock.put("i_Out", new Boolean(false));
			if (!(Boolean)lock.get("i_Out")){
				lock.put("i_Out", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"i_Out");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"I_Out");
					i_Out= val;
			}
		return i_Out;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setI_Out(String newI_Out) {
		String oldI_Out = i_Out;
		i_Out = newI_Out;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__IOUT, oldI_Out, i_Out));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getVA_Out() {
		// Generated by python script located in this directory
			if (!lock.containsKey("vA_Out")) lock.put("vA_Out", new Boolean(false));
			if (!(Boolean)lock.get("vA_Out")){
				lock.put("vA_Out", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"vA_Out");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"VA_Out");
					vA_Out= val;
			}
		return vA_Out;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setVA_Out(String newVA_Out) {
		String oldVA_Out = vA_Out;
		vA_Out = newVA_Out;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__VA_OUT, oldVA_Out, vA_Out));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getV_In() {
		// Generated by python script located in this directory
			if (!lock.containsKey("v_In")) lock.put("v_In", new Boolean(false));
			if (!(Boolean)lock.get("v_In")){
				lock.put("v_In", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"v_In");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"V_In");
					v_In= val;
			}
		return v_In;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setV_In(String newV_In) {
		String oldV_In = v_In;
		v_In = newV_In;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__VIN, oldV_In, v_In));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getI_In() {
		// Generated by python script located in this directory
			if (!lock.containsKey("i_In")) lock.put("i_In", new Boolean(false));
			if (!(Boolean)lock.get("i_In")){
				lock.put("i_In", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"i_In");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"I_In");
					i_In= val;
			}
		return i_In;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setI_In(String newI_In) {
		String oldI_In = i_In;
		i_In = newI_In;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__IIN, oldI_In, i_In));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getV_Internal() {
		// Generated by python script located in this directory
			if (!lock.containsKey("v_Internal")) lock.put("v_Internal", new Boolean(false));
			if (!(Boolean)lock.get("v_Internal")){
				lock.put("v_Internal", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"v_Internal");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"V_Internal");
					v_Internal= val;
			}
		return v_Internal;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setV_Internal(String newV_Internal) {
		String oldV_Internal = v_Internal;
		v_Internal = newV_Internal;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__VINTERNAL, oldV_Internal, v_Internal));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getI_Internal() {
		// Generated by python script located in this directory
			if (!lock.containsKey("i_Internal")) lock.put("i_Internal", new Boolean(false));
			if (!(Boolean)lock.get("i_Internal")){
				lock.put("i_Internal", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"i_Internal");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"I_Internal");
					i_Internal= val;
			}
		return i_Internal;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setI_Internal(String newI_Internal) {
		String oldI_Internal = i_Internal;
		i_Internal = newI_Internal;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__IINTERNAL, oldI_Internal, i_Internal));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getI_Prev() {
		// Generated by python script located in this directory
			if (!lock.containsKey("i_Prev")) lock.put("i_Prev", new Boolean(false));
			if (!(Boolean)lock.get("i_Prev")){
				lock.put("i_Prev", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"i_Prev");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"I_Prev");
					i_Prev= val;
			}
		return i_Prev;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setI_Prev(String newI_Prev) {
		String oldI_Prev = i_Prev;
		i_Prev = newI_Prev;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__IPREV, oldI_Prev, i_Prev));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getPhases() {
		// Generated by python script located in this directory
			if (!lock.containsKey("phases")) lock.put("phases", new Boolean(false));
			if (!(Boolean)lock.get("phases")){
				lock.put("phases", true);
				checkUnlock();
					String val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"phases");
					if (val == null) val = http.Property.getValueOfProperty(this.getName().replace(" ", "%20"),"Phases");
					phases= val;
			}
		return phases;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setPhases(String newPhases) {
		String oldPhases = phases;
		phases = newPhases;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, VisGridPackage.BATTERY__PHASES, oldPhases, phases));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case VisGridPackage.BATTERY__GENERATOR_MODE:
				return getGenerator_mode();
			case VisGridPackage.BATTERY__GENERATOR_STATUS:
				return getGenerator_status();
			case VisGridPackage.BATTERY__RFB_SIZE:
				return getRfb_size();
			case VisGridPackage.BATTERY__POWER_TYPE:
				return getPower_type();
			case VisGridPackage.BATTERY__POWER_SET_HIGH:
				return getPower_set_high();
			case VisGridPackage.BATTERY__POWER_SET_LOW:
				return getPower_set_low();
			case VisGridPackage.BATTERY__RINTERNAL:
				return getRinternal();
			case VisGridPackage.BATTERY__VMAX:
				return getV_Max();
			case VisGridPackage.BATTERY__IMAX:
				return getI_Max();
			case VisGridPackage.BATTERY__EMAX:
				return getE_Max();
			case VisGridPackage.BATTERY__ENERGY:
				return getEnergy();
			case VisGridPackage.BATTERY__EFFICIENCY:
				return getEfficiency();
			case VisGridPackage.BATTERY__BASE_EFFICIENCY:
				return getBase_efficiency();
			case VisGridPackage.BATTERY__RATED_KVA:
				return getRated_kVA();
			case VisGridPackage.BATTERY__VOUT:
				return getV_Out();
			case VisGridPackage.BATTERY__IOUT:
				return getI_Out();
			case VisGridPackage.BATTERY__VA_OUT:
				return getVA_Out();
			case VisGridPackage.BATTERY__VIN:
				return getV_In();
			case VisGridPackage.BATTERY__IIN:
				return getI_In();
			case VisGridPackage.BATTERY__VINTERNAL:
				return getV_Internal();
			case VisGridPackage.BATTERY__IINTERNAL:
				return getI_Internal();
			case VisGridPackage.BATTERY__IPREV:
				return getI_Prev();
			case VisGridPackage.BATTERY__PHASES:
				return getPhases();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case VisGridPackage.BATTERY__GENERATOR_MODE:
				setGenerator_mode((String)newValue);
				return;
			case VisGridPackage.BATTERY__GENERATOR_STATUS:
				setGenerator_status((String)newValue);
				return;
			case VisGridPackage.BATTERY__RFB_SIZE:
				setRfb_size((String)newValue);
				return;
			case VisGridPackage.BATTERY__POWER_TYPE:
				setPower_type((String)newValue);
				return;
			case VisGridPackage.BATTERY__POWER_SET_HIGH:
				setPower_set_high((String)newValue);
				return;
			case VisGridPackage.BATTERY__POWER_SET_LOW:
				setPower_set_low((String)newValue);
				return;
			case VisGridPackage.BATTERY__RINTERNAL:
				setRinternal((String)newValue);
				return;
			case VisGridPackage.BATTERY__VMAX:
				setV_Max((String)newValue);
				return;
			case VisGridPackage.BATTERY__IMAX:
				setI_Max((String)newValue);
				return;
			case VisGridPackage.BATTERY__EMAX:
				setE_Max((String)newValue);
				return;
			case VisGridPackage.BATTERY__ENERGY:
				setEnergy((String)newValue);
				return;
			case VisGridPackage.BATTERY__EFFICIENCY:
				setEfficiency((String)newValue);
				return;
			case VisGridPackage.BATTERY__BASE_EFFICIENCY:
				setBase_efficiency((String)newValue);
				return;
			case VisGridPackage.BATTERY__RATED_KVA:
				setRated_kVA((String)newValue);
				return;
			case VisGridPackage.BATTERY__VOUT:
				setV_Out((String)newValue);
				return;
			case VisGridPackage.BATTERY__IOUT:
				setI_Out((String)newValue);
				return;
			case VisGridPackage.BATTERY__VA_OUT:
				setVA_Out((String)newValue);
				return;
			case VisGridPackage.BATTERY__VIN:
				setV_In((String)newValue);
				return;
			case VisGridPackage.BATTERY__IIN:
				setI_In((String)newValue);
				return;
			case VisGridPackage.BATTERY__VINTERNAL:
				setV_Internal((String)newValue);
				return;
			case VisGridPackage.BATTERY__IINTERNAL:
				setI_Internal((String)newValue);
				return;
			case VisGridPackage.BATTERY__IPREV:
				setI_Prev((String)newValue);
				return;
			case VisGridPackage.BATTERY__PHASES:
				setPhases((String)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case VisGridPackage.BATTERY__GENERATOR_MODE:
				setGenerator_mode(GENERATOR_MODE_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__GENERATOR_STATUS:
				setGenerator_status(GENERATOR_STATUS_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__RFB_SIZE:
				setRfb_size(RFB_SIZE_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__POWER_TYPE:
				setPower_type(POWER_TYPE_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__POWER_SET_HIGH:
				setPower_set_high(POWER_SET_HIGH_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__POWER_SET_LOW:
				setPower_set_low(POWER_SET_LOW_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__RINTERNAL:
				setRinternal(RINTERNAL_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__VMAX:
				setV_Max(VMAX_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__IMAX:
				setI_Max(IMAX_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__EMAX:
				setE_Max(EMAX_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__ENERGY:
				setEnergy(ENERGY_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__EFFICIENCY:
				setEfficiency(EFFICIENCY_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__BASE_EFFICIENCY:
				setBase_efficiency(BASE_EFFICIENCY_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__RATED_KVA:
				setRated_kVA(RATED_KVA_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__VOUT:
				setV_Out(VOUT_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__IOUT:
				setI_Out(IOUT_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__VA_OUT:
				setVA_Out(VA_OUT_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__VIN:
				setV_In(VIN_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__IIN:
				setI_In(IIN_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__VINTERNAL:
				setV_Internal(VINTERNAL_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__IINTERNAL:
				setI_Internal(IINTERNAL_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__IPREV:
				setI_Prev(IPREV_EDEFAULT);
				return;
			case VisGridPackage.BATTERY__PHASES:
				setPhases(PHASES_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case VisGridPackage.BATTERY__GENERATOR_MODE:
				return GENERATOR_MODE_EDEFAULT == null ? generator_mode != null : !GENERATOR_MODE_EDEFAULT.equals(generator_mode);
			case VisGridPackage.BATTERY__GENERATOR_STATUS:
				return GENERATOR_STATUS_EDEFAULT == null ? generator_status != null : !GENERATOR_STATUS_EDEFAULT.equals(generator_status);
			case VisGridPackage.BATTERY__RFB_SIZE:
				return RFB_SIZE_EDEFAULT == null ? rfb_size != null : !RFB_SIZE_EDEFAULT.equals(rfb_size);
			case VisGridPackage.BATTERY__POWER_TYPE:
				return POWER_TYPE_EDEFAULT == null ? power_type != null : !POWER_TYPE_EDEFAULT.equals(power_type);
			case VisGridPackage.BATTERY__POWER_SET_HIGH:
				return POWER_SET_HIGH_EDEFAULT == null ? power_set_high != null : !POWER_SET_HIGH_EDEFAULT.equals(power_set_high);
			case VisGridPackage.BATTERY__POWER_SET_LOW:
				return POWER_SET_LOW_EDEFAULT == null ? power_set_low != null : !POWER_SET_LOW_EDEFAULT.equals(power_set_low);
			case VisGridPackage.BATTERY__RINTERNAL:
				return RINTERNAL_EDEFAULT == null ? rinternal != null : !RINTERNAL_EDEFAULT.equals(rinternal);
			case VisGridPackage.BATTERY__VMAX:
				return VMAX_EDEFAULT == null ? v_Max != null : !VMAX_EDEFAULT.equals(v_Max);
			case VisGridPackage.BATTERY__IMAX:
				return IMAX_EDEFAULT == null ? i_Max != null : !IMAX_EDEFAULT.equals(i_Max);
			case VisGridPackage.BATTERY__EMAX:
				return EMAX_EDEFAULT == null ? e_Max != null : !EMAX_EDEFAULT.equals(e_Max);
			case VisGridPackage.BATTERY__ENERGY:
				return ENERGY_EDEFAULT == null ? energy != null : !ENERGY_EDEFAULT.equals(energy);
			case VisGridPackage.BATTERY__EFFICIENCY:
				return EFFICIENCY_EDEFAULT == null ? efficiency != null : !EFFICIENCY_EDEFAULT.equals(efficiency);
			case VisGridPackage.BATTERY__BASE_EFFICIENCY:
				return BASE_EFFICIENCY_EDEFAULT == null ? base_efficiency != null : !BASE_EFFICIENCY_EDEFAULT.equals(base_efficiency);
			case VisGridPackage.BATTERY__RATED_KVA:
				return RATED_KVA_EDEFAULT == null ? rated_kVA != null : !RATED_KVA_EDEFAULT.equals(rated_kVA);
			case VisGridPackage.BATTERY__VOUT:
				return VOUT_EDEFAULT == null ? v_Out != null : !VOUT_EDEFAULT.equals(v_Out);
			case VisGridPackage.BATTERY__IOUT:
				return IOUT_EDEFAULT == null ? i_Out != null : !IOUT_EDEFAULT.equals(i_Out);
			case VisGridPackage.BATTERY__VA_OUT:
				return VA_OUT_EDEFAULT == null ? vA_Out != null : !VA_OUT_EDEFAULT.equals(vA_Out);
			case VisGridPackage.BATTERY__VIN:
				return VIN_EDEFAULT == null ? v_In != null : !VIN_EDEFAULT.equals(v_In);
			case VisGridPackage.BATTERY__IIN:
				return IIN_EDEFAULT == null ? i_In != null : !IIN_EDEFAULT.equals(i_In);
			case VisGridPackage.BATTERY__VINTERNAL:
				return VINTERNAL_EDEFAULT == null ? v_Internal != null : !VINTERNAL_EDEFAULT.equals(v_Internal);
			case VisGridPackage.BATTERY__IINTERNAL:
				return IINTERNAL_EDEFAULT == null ? i_Internal != null : !IINTERNAL_EDEFAULT.equals(i_Internal);
			case VisGridPackage.BATTERY__IPREV:
				return IPREV_EDEFAULT == null ? i_Prev != null : !IPREV_EDEFAULT.equals(i_Prev);
			case VisGridPackage.BATTERY__PHASES:
				return PHASES_EDEFAULT == null ? phases != null : !PHASES_EDEFAULT.equals(phases);
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuffer result = new StringBuffer(super.toString());
		result.append(" (generator_mode: ");
		result.append(generator_mode);
		result.append(", generator_status: ");
		result.append(generator_status);
		result.append(", rfb_size: ");
		result.append(rfb_size);
		result.append(", power_type: ");
		result.append(power_type);
		result.append(", power_set_high: ");
		result.append(power_set_high);
		result.append(", power_set_low: ");
		result.append(power_set_low);
		result.append(", Rinternal: ");
		result.append(rinternal);
		result.append(", V_Max: ");
		result.append(v_Max);
		result.append(", I_Max: ");
		result.append(i_Max);
		result.append(", E_Max: ");
		result.append(e_Max);
		result.append(", Energy: ");
		result.append(energy);
		result.append(", efficiency: ");
		result.append(efficiency);
		result.append(", base_efficiency: ");
		result.append(base_efficiency);
		result.append(", Rated_kVA: ");
		result.append(rated_kVA);
		result.append(", V_Out: ");
		result.append(v_Out);
		result.append(", I_Out: ");
		result.append(i_Out);
		result.append(", VA_Out: ");
		result.append(vA_Out);
		result.append(", V_In: ");
		result.append(v_In);
		result.append(", I_In: ");
		result.append(i_In);
		result.append(", V_Internal: ");
		result.append(v_Internal);
		result.append(", I_Internal: ");
		result.append(i_Internal);
		result.append(", I_Prev: ");
		result.append(i_Prev);
		result.append(", phases: ");
		result.append(phases);
		result.append(')');
		return result.toString();
	}

} //BatteryImpl
