import sys 
import re
import shutil

if (len(sys.argv) <2):
    sys.exit(0)

r = open(sys.argv[1],'r')
w = open(sys.argv[1]+'.swp','w')


for line in r:

    w.write(line)

    if "package " in line:
        w.write('import java.util.Timer;\n')
        w.write('import java.util.TimerTask;\n')

    if 'public class ' in line:
        w.write('\t\tboolean lock = false;\n')

    search = re.search('String get(\w+)\(\) \{', line)
    if search:
        key = search.group(1)
        print 'Adding http get for '+key
        w.write('\t\t// Generated by python script located in this directory\n')
        w.write('\t\tif (!lock){\n')
        w.write('\t\t\ttry {\n')
        w.write('\t\t\t\tString val = http.Property.getValueOfProperty(this.getName(),"'+key[0:1].lower()+key[1:]+'");\n');
        w.write('\t\t\t\tif (val == null) val = http.Property.getValueOfProperty(this.getName(),"'+key[0:1].lower()+key[1:]+'");\n')
        w.write('\t\t\t\tif (val == null) val = http.Property.getValueOfProperty(this.getName(),"'+(key[0:1].lower()+key[1:]).replace("__","%20")+'");\n')
        w.write('\t\t\t\tif (val == null) val = http.Property.getValueOfProperty(this.getName(),"'+(key).replace("__","%20")+'");\n')
        w.write('\t\t\t\t'+key[0:1].lower()+key[1:]+'= val;\n');
        w.write('\t\t\t} catch (Exception e) {\n\t\t\t\tthis.set'+key+'("unknown");\n\t\t\t\te.printStackTrace();\n\t\t\t}\n')
        w.write('\t\t}\n')
r.close()
w.close()
shutil.move(sys.argv[1]+'.swp',sys.argv[1])
