#!/bin/bash

rm -R web/CVS
rm -R web/.cvsignore
rm -R web/*/CVS
rm -R web/*/.cvsignore
rm -R web/*/*/CVS
rm -R web/*/*/.cvsignore
rm -R web/*/*/*/CVS
rm -R web/*/*/*/.cvsignore
rm -R web/*/*/*/*/CVS
rm -R web/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/CVS
rm -R web/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/.cvsignore